# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Jimo' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
  use_modular_headers!

  # Pods for Jimo
  pod 'Firebase/Auth'
  pod 'Firebase/Messaging'
  pod 'Firebase/Storage'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Analytics'

  pod 'SDWebImage'
  pod 'SDWebImageSwiftUI'

  pod 'PhoneNumberKit', '~> 3.3'

  target 'JimoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JimoUITests' do
    # Pods for testing
  end

end
