# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Jimo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Jimo
  pod 'Firebase/Auth'

  target 'JimoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JimoUITests' do
    # Pods for testing
  end

end
